name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'

permissions:
  contents: read

concurrency:
  group: quality-checks-${{ github.ref }}-${{ github.event.pull_request.number || 'no-pr' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  quality-spotless:
    name: Spotless check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Spotless
        run: ./gradlew spotlessCheck

  quality-detekt:
    name: Detekt check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Detekt
        run: ./gradlew detektAll

  quality-coverage:
    name: Code coverage check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Code coverage
        run: ./gradlew koverVerify

  quality-konsist:
    name: Konsist check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Konsist
        run: ./gradlew :quality:konsist:test
